### ISSUE TITLE
Armor Stands cause crash

### ISSUE THREAD

**Issue by brisingraerowing** [Thelnfamous1/Mob-Player-Animator#1]
[Crash Log](https://gist.github.com/brisingraerowing/6edf16067c61f6ef08e11d7bd7f40dce)

Probably need to blacklist them by default.

**Comment by Thelnfamous1** [comment]
Fixed by 569105a

**Comment by Thelnfamous1** [comment]
1.0.1 containing the fix has been released, now available on Modrinth and Curseforge  (pending approval). 

Thanks for reporting!
