### ISSUE TITLE
More animations!

### ISSUE THREAD

**Issue by Aurarobe** [Thelnfamous1/Mob-Player-Animator#10]
Is it possible to make other Player Animator animations able to run on the entity aswell? like if the user have a player animation mod that uses Player Animator, the affected mobs will be able to have them too!

**Comment by Thelnfamous1** [comment]
It would require other mods to be made to add the custom player animations to the mobs. Mob Player Animator, like Player Animater, does not do that by itself. It simply provides the system to apply such animations.
