### ISSUE TITLE
I found an animation-related error when interacting with Mob Player Animator and all the Bark, All Bite mods

### ISSUE THREAD

**Issue by MammothPeter1051** [Thelnfamous1/Mob-Player-Animator#4]
![2024-07-10_06 27 33](https://github.com/Thelnfamous1/Mob-Player-Animator/assets/175315965/ee7070b7-3918-456f-84ad-8bdd8774efab)

**Comment by Thelnfamous1** [comment]
Duplicate of #3

**Comment by Thelnfamous1** [comment]
Fixed by 703f477. Be on the lookout for version 1.2.1 which will include this fix.
