### ISSUE TITLE
newest update causes vindicator to be armless after FA fix

### ISSUE THREAD

**Issue by YnwLNE** [Thelnfamous1/Mob-Player-Animator#5]
Applying the update and following the directions (removing vindicator from the "emf_force_vanilla_models") does fix the facial animations but ends up breaking the arms by making them disappear during swings

![image](https://github.com/Thelnfamous1/Mob-Player-Animator/assets/81484850/abe1065d-c15d-42bd-b929-90e75a91d2e6)
![huge_2024-07-11_09 18 10](https://github.com/Thelnfamous1/Mob-Player-Animator/assets/81484850/8e067cd7-35ee-45d9-b1b3-6207d4dfbb10)

**Comment by YnwLNE** [comment]
Tested with different versions of FA, the latest fixes the arms but the axe still randomly disappears for a split second. 

Guard Villagers are broken if you're using the FA addon https://modrinth.com/resourcepack/freshly-modded  (latest version) but that's to be expected as that's not officially supported.

Feel free to close this commit.

In other words, this mod has quickly become one of my favorite mods to include life and immersion into a mostly static game, thank you for you work!

**Comment by Thelnfamous1** [comment]
I was testing with the latest version of Fresh Animations for 1.20.1, which is 1.9.2, so that's what the Vindicator model modifier in the config was made for.

I noticed the brief disappearance of the weapon, that is likely due to the vanilla AI for the Vindicator. I will look into a fix for it.

Guard Villagers are completely fine if you use Fresh Friends, that's what I tested with. You can move Fresh Friends higher in the Resource Pack hierarchy and it will override the Freshly Modded model for them. 

If you prefer the Freshly Modded model, you will need to make an entry in the `emf_model_modifiers` config for Guard Villagers that makes the necessary adjustments.

**Comment by Thelnfamous1** [comment]
I'll keep this open until I fix the weapon disappearance bug for Vindicators.

**Comment by YnwLNE** [comment]
> I was testing with the latest version of Fresh Animations for 1.20.1, which is 1.9.2, so that's what the Vindicator model modifier in the config was made for.
> 
> I noticed the brief disappearance of the weapon, that is likely due to the vanilla AI for the Vindicator. I will look into a fix for it.
> 
> Guard Villagers are completely fine if you use Fresh Friends, that's what I tested with. You can move Fresh Friends higher in the Resource Pack hierarchy and it will override the Freshly Modded model for them. If you prefer the Fresh Friends model, you will need to make an entry in the `emf_model_modifiers` config for Guard Villagers that makes the necessary adjustments.

Haven't heard of Fresh Friends but I'll look into adding it to the emf_model_modifiers and possibly the one from Freshly Modded as well since it doesn't like being stacked with FF, thank you for the guidance!

**Comment by Thelnfamous1** [comment]
I made an error in my sentence about adding the Guard Villager to the config. I meant to say if you prefer the Freshly Modded model, then you will need to make an `emf_model_modifiers`entry for Guard Villagers. The Fresh Friends model needs no adjustments.

**Comment by YnwLNE** [comment]
Dw, I caught onto that! Partially got it working and now just needs tinkering with the part_modifiers.

**Comment by Thelnfamous1** [comment]
> I'll keep this open until I fix the weapon disappearance bug for Vindicators.

This will be fixed in Better Mob Combat 1.2.0, as the fix was more suitable to be implemented there.
