### ISSUE TITLE
Does not work with the new EMF 2.2 update

### ISSUE THREAD

**Issue by YeraX7** [Thelnfamous1/Mob-Player-Animator#7]
In short, I have updated EMF and ETF to the latest version and when I open minecraft it gives a crash error that docer that there is some problem of Mob player animation with EMF.

[crash-2024-08-20_23.55.34-fml.txt](https://github.com/user-attachments/files/16682753/crash-2024-08-20_23.55.34-fml.txt)

**Comment by Thelnfamous1** [comment]
Update your Mob Player Animator version to 1.2.2.
