### ISSUE TITLE
Persistent model changes bug

### ISSUE THREAD

**Issue by Sylthena** [Thelnfamous1/Mob-Player-Animator#9]
![8B5DCE9D-A0FA-4D61-A9E9-5DBA10EAA980](https://github.com/user-attachments/assets/005d8592-53d7-49e6-a2c7-835b9468c21e)
MCA villagers after using any Better Combat item retain some model changes from that item's animation, in this case a massive thigh gap after using a katana. This model change is applied to every entity with that same ID, not just that single entity.

**Comment by Thelnfamous1** [comment]
Will be fixed in version 1.3.1!
